name: SomeBoard
services:
  backend:
    image: somebord.backend:latest
    container_name: SomeBoard.Backend
    build:
      context: .
      dockerfile: SomeBoard.Backend/Dockerfile
    ports: 
      - "$BACKEND_HTTP_PORT:9001"
    # If you want to use HTTPS, remove # from lines below
    #  - "$BACKEND_HTTPS_PORT:9000"
    #extends:
    #  file: https.yml
    #  service: https_backend
    volumes:
      - "$BACKEND_CONFIG:/app/appsettings.json"
      - "$BACKEND_LOGS:/app/logs/"
    environment: 
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ASPNETCORE_HTTP_PORTS=${BACKEND_HTTP_PORT}"
      - "SomeBoard.Posting.Host=SomeBoard.Database"
      - "SomeBoard.Posting.Username=${DATABASE_USERNAME}"
      - "SomeBoard.Posting.Database=${DATABASE_NAME}"
      - "SomeBoard.Posting.Password=${DATABASE_PASSWORD}"
      # If you want to use passfile, remove # from line below
      #- "SomeBoard.Posting.PasswordFile=${DATABASE_PASSFILE}"
      - "SomeBoard.Posting.AdminSecretFile=${BACKEND_ADMINSECRET}"
    # If you want to use HTTPS, remove # from lines below
    #  - "ASPNETCORE_HTTPS_PORTS=${BACKEND_HTTPS_PORT}"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
  
  frontend:
    image: someboard.frontend:latest
    container_name: SomeBoard.Frontend
    build:
      context: .
      dockerfile: SomeBoard.Frontend/Dockerfile
    ports:
      - "$FRONTEND_HTTP_PORT:80"
    # If you want to use HTTPS, remove # from lines below
    #  - "$FRONTEND_HTTPS_PORT:443"
    #extends:
    #  file: https.yml
    #  service: https_frontend
    volumes:
      - "$FRONTEND_CONFIG:/app/appsettings.json"
      - "$FRONTEND_LOGS:/app/logs/"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ASPNETCORE_HTTP_PORTS=${FRONTEND_HTTP_PORT}"
      # If you want to use HTTPS, remove # from lines below
      #  - "ASPNETCORE_HTTPS_PORTS=${FRONTEND_HTTPS_PORT}"
    restart: unless-stopped
    env_file:
      - .env
  postgres:
    container_name: SomeBoard.Database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      # If you want to use passfile, comment line above and remove # from line below
      # POSTGRES_PASSFILE: ${DATABASE_PASSFILE}
      # If your database isn't stored on SSDs, remove # from line below
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
        - ${DATABASE_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped