services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: SomeBoard.Backend/Dockerfile
    ports: 
      - "$BACKEND_HTTP_PORT:9001"
      # If you want to use HTTPS, remove # from line below
      # - "$BACKEND_HTTPS_PORT:9000"
    volumes:
      - "$BACKEND_CONFIG:/app/appsettings.json"
      - "$BACKEND_LOGS:/app/logs/"
  
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: SomeBoard.Backend/Dockerfile
    ports:
      - "$FRONTEND_HTTP_PORT:80"
      # If you want to use HTTPS, remove # from line below
      # - "$FRONTEND_HTTPS_PORT:443"
    volumes:
      - "$FRONTEND_CONFIG:/app/appsettings.json"
      - "$FRONTEND_LOGS:/app/logs/"
